version: '3.8'

services:
  db:
    image: postgres:13-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ai_interview_development
    ports:
      - "5432:5432"

  redis:
    image: redis:6-alpine
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/ai_interview_development
      REDIS_URL: redis://redis:6379/1

volumes:
  db-data:
  redis-data:
