/** @type {import('tailwindcss').Config} */
export default {
    darkMode: ["class"],
    content: ["./index.html", "./src/**/*.{ts,tsx}"],
    theme: {
        extend: {
            colors: {
                border: "hsl(var(--hairline))",
                input: "hsl(var(--hairline))",
                ring: "hsl(var(--ring))",
                background: "hsl(var(--canvas))",
                foreground: "hsl(var(--ink))",

                primary: {
                    DEFAULT: "hsl(var(--primary))",
                    deep: "hsl(var(--primary-deep))",
                    soft: "hsl(var(--primary-soft))",
                    foreground: "hsl(var(--on-primary))",
                },
                secondary: {
                    DEFAULT: "hsl(var(--ink-mute))",
                    foreground: "hsl(var(--on-dark))",
                },
                destructive: {
                    DEFAULT: "hsl(var(--accent-tomato))",
                    foreground: "hsl(var(--on-dark))",
                },
                muted: {
                    DEFAULT: "hsl(var(--canvas-soft))",
                    foreground: "hsl(var(--ink-mute))",
                },
                accent: {
                    DEFAULT: "hsl(var(--accent-purple))",
                    purple: "hsl(var(--accent-purple))",
                    violet: "hsl(var(--accent-violet))",
                    yellow: "hsl(var(--accent-yellow))",
                    tomato: "hsl(var(--accent-tomato))",
                    pink: "hsl(var(--accent-pink))",
                    indigo: "hsl(var(--accent-indigo))",
                    crimson: "hsl(var(--accent-crimson))",
                    purpleSoft: "hsl(var(--accent-purple-soft))",
                    foreground: "hsl(var(--on-dark))",
                },
                card: {
                    DEFAULT: "hsl(var(--canvas))",
                    foreground: "hsl(var(--ink))",
                },
                popover: {
                    DEFAULT: "hsl(var(--canvas))",
                    foreground: "hsl(var(--ink))",
                },
                ink: {
                    DEFAULT: "hsl(var(--ink))",
                    secondary: "hsl(var(--ink-secondary))",
                    mute: "hsl(var(--ink-mute))",
                    'mute-2': "hsl(var(--ink-mute-2))",
                    faint: "hsl(var(--ink-faint))",
                },
                canvas: {
                    DEFAULT: "hsl(var(--canvas))",
                    soft: "hsl(var(--canvas-soft))",
                    night: "hsl(var(--canvas-night))",
                    nightSoft: "hsl(var(--canvas-night-soft))",
                },
                hairline: {
                    DEFAULT: "hsl(var(--hairline))",
                    strong: "hsl(var(--hairline-strong))",
                    cool: "hsl(var(--hairline-cool))",
                    'cool-2': "hsl(var(--hairline-cool-2))",
                    'cool-3': "hsl(var(--hairline-cool-3))",
                },
                on: {
                    primary: "hsl(var(--on-primary))",
                    dark: "hsl(var(--on-dark))",
                }
            },
            borderRadius: {
                lg: "var(--radius)",
                md: "calc(var(--radius) - 2px)",
                sm: "calc(var(--radius) - 4px)",
                'xs': '4px',
                'sm': '6px',
                'md': '8px',
                'lg': '12px',
                'xl': '16px',
                'full': '9999px',
            },
            fontFamily: {
                sans: ['Circular', 'Inter', 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'],
                mono: ['ui-monospace', 'Menlo', 'Monaco', 'Consolas', 'Liberation Mono', 'monospace'],
            },
            fontSize: {
                'display-xxl': ['64px', { lineHeight: '1.1', letterSpacing: '-1.92px' }],
                'display-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-1.44px' }],
                'display-lg': ['36px', { lineHeight: '1.15', letterSpacing: '-0.72px' }],
                'display-md': ['28px', { lineHeight: '1.2', letterSpacing: '-0.42px' }],
                'heading-lg': ['22px', { lineHeight: '1.2', letterSpacing: '0' }],
                'heading-md': ['18px', { lineHeight: '1.4', letterSpacing: '0' }],
                'body-lg': ['18px', { lineHeight: '1.55', letterSpacing: '0' }],
                'body-md': ['16px', { lineHeight: '1.5', letterSpacing: '0' }],
                'button-md': ['14px', { lineHeight: '1.0', letterSpacing: '0' }],
                'caption': ['13px', { lineHeight: '1.45', letterSpacing: '0' }],
                'micro': ['12px', { lineHeight: '1.45', letterSpacing: '0' }],
                'code': ['14px', { lineHeight: '1.5', letterSpacing: '0' }],
            },
            lineHeight: {
                'display-xxl': '1.1',
                'display-xl': '1.1',
                'display-lg': '1.15',
                'display-md': '1.2',
                'heading-lg': '1.2',
                'heading-md': '1.4',
                'body-lg': '1.55',
                'body-md': '1.5',
                'button-md': '1.0',
                'caption': '1.45',
                'micro': '1.45',
                'code': '1.5',
            },
            letterSpacing: {
                'display-xxl': '-1.92px',
                'display-xl': '-1.44px',
                'display-lg': '-0.72px',
                'display-md': '-0.42px',
                'heading-lg': '0',
                'heading-md': '0',
                'body-lg': '0',
                'body-md': '0',
                'button-md': '0',
                'caption': '0',
                'micro': '0',
                'code': '0',
            },
            spacing: {
                'xxs': '2px',
                'xs': '4px',
                'sm': '8px',
                'md': '12px',
                'lg': '16px',
                'xl': '24px',
                'xxl': '32px',
                'huge': '64px',
            },
            keyframes: {
                "accordion-down": {
                    from: { height: "0" },
                    to: { height: "var(--radix-accordion-content-height)" },
                },
                "accordion-up": {
                    from: { height: "var(--radix-accordion-content-height)" },
                    to: { height: "0" },
                },
                "voice-bar": {
                    "0%, 100%": { height: "4px" },
                    "50%": { height: "32px" },
                },
            },
            animation: {
                "accordion-down": "accordion-down 0.2s ease-out",
                "accordion-up": "accordion-up 0.2s ease-out",
                "voice-bar": "voice-bar 0.8s ease-in-out infinite",
            },
        },
    },
    plugins: [require("tailwindcss-animate")],
};
